# ESTÁGIO 1: Build (Usando a versão completa do Node para evitar erros de compilação)
FROM node:20 as builder

WORKDIR /app

# Copia apenas os arquivos de configuração primeiro (o asterisco garante que pegue o lock também)
COPY package*.json ./

# Usa install com flag para ignorar conflitos chatos de bibliotecas
RUN npm install --legacy-peer-deps

# Copia o resto do código
COPY . .

# Roda o build do Vite
RUN npm run build

# ESTÁGIO 2: Nginx (Servidor Web - aqui mantemos o alpine para ficar ultra leve)
FROM nginx:alpine

# Remove as configurações padrão
RUN rm -rf /etc/nginx/conf.d/*

# Copia sua configuração
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia os arquivos gerados no estágio 1
COPY --from=builder /app/dist /usr/share/nginx/html

# Libera a porta 80
EXPOSE 80

# Inicia o Nginx
CMD ["nginx", "-g", "daemon off;"]
