version: '3.8'

services:
  html-helper-frontend:
    build: .
    container_name: html-helper-app
    restart: unless-stopped
    ports:
      - "80:80" # Mapeia a porta 80 da VPS para a porta 80 do container
    # Se você já usa a porta 80 na VPS para outra coisa, mude para "8080:80", por exemplo.