# ESTÁGIO 1: Build (Construção do projeto)
FROM node:20-alpine as builder

WORKDIR /app

# Copia os arquivos de dependência e instala
COPY package.json package-lock.json ./
RUN npm install

# Copia o resto do código e faz o build (Vite vai gerar a pasta /dist)
COPY . .
RUN npm run build

# ESTÁGIO 2: Nginx (Servidor Web)
FROM nginx:alpine

# Remove as configurações padrão do Nginx
RUN rm -rf /etc/nginx/conf.d/*

# Copia aquele seu arquivo nginx.conf para dentro do container
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copia os arquivos "buildados" do estágio 1 para a pasta pública do Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Expõe a porta 80
EXPOSE 80

# Inicia o Nginx
CMD ["nginx", "-g", "daemon off;"]